import { defaultProvider } from "@/providers"

const mockOrganizations = [
  {
    OrganisationId: "org-001",
    OrganisationName: "TechCorp Solutions",
    LegalEntityName: "TechCorp Solutions Ltda",
    RegistrationNumber: "12345678901234",
    RegistrationId: "REG-001",
    AddressLine1: "Av. Paulista, 1000",
    AddressLine2: "Bela Vista",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Open Banking"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-002",
    OrganisationName: "Digital Finance",
    LegalEntityName: "Digital Finance S.A.",
    RegistrationNumber: "98765432109876",
    RegistrationId: "REG-002",
    AddressLine1: "Av. Rio Branco, 500",
    AddressLine2: "Centro",
    City: "Rio de Janeiro, RJ",
    Country: "Brasil",
    Tags: ["Banking", "Digital"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-003",
    OrganisationName: "Innovate Payments",
    LegalEntityName: "Innovate Payments Tecnologia Ltda",
    RegistrationNumber: "45678912345678",
    RegistrationId: "REG-003",
    AddressLine1: "Rua Augusta, 2000",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Technology"],
    Size: "Pequeno",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-004",
    OrganisationName: "Smart Banking",
    LegalEntityName: "Smart Banking Tecnologia S.A.",
    RegistrationNumber: "23456789012345",
    RegistrationId: "REG-004",
    AddressLine1: "Av. Brigadeiro Faria Lima, 1500",
    AddressLine2: "Jardim Paulistano",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Technology"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-005",
    OrganisationName: "SecurePay",
    LegalEntityName: "SecurePay Sistemas Ltda",
    RegistrationNumber: "34567890123456",
    RegistrationId: "REG-005",
    AddressLine1: "Rua Oscar Freire, 800",
    AddressLine2: "Jardins",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Security"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-006",
    OrganisationName: "FinTech Brasil",
    LegalEntityName: "FinTech Brasil Inovação S.A.",
    RegistrationNumber: "45678901234567",
    RegistrationId: "REG-006",
    AddressLine1: "Av. Rebouças, 1000",
    AddressLine2: "Pinheiros",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Innovation"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-007",
    OrganisationName: "Digital Bank",
    LegalEntityName: "Digital Bank Serviços Financeiros Ltda",
    RegistrationNumber: "56789012345678",
    RegistrationId: "REG-007",
    AddressLine1: "Av. Berrini, 1500",
    AddressLine2: "Brooklin",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Digital"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-008",
    OrganisationName: "PayTech",
    LegalEntityName: "PayTech Soluções Ltda",
    RegistrationNumber: "67890123456789",
    RegistrationId: "REG-008",
    AddressLine1: "Rua Haddock Lobo, 400",
    AddressLine2: "Cerqueira César",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Technology"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-009",
    OrganisationName: "BankTech",
    LegalEntityName: "BankTech Inovação S.A.",
    RegistrationNumber: "78901234567890",
    RegistrationId: "REG-009",
    AddressLine1: "Av. Cidade Jardim, 200",
    AddressLine2: "Jardim Europa",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Technology"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-010",
    OrganisationName: "FinSecure",
    LegalEntityName: "FinSecure Sistemas Ltda",
    RegistrationNumber: "89012345678901",
    RegistrationId: "REG-010",
    AddressLine1: "Rua Bela Cintra, 1000",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Security"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-011",
    OrganisationName: "TechBank",
    LegalEntityName: "TechBank Soluções S.A.",
    RegistrationNumber: "90123456789012",
    RegistrationId: "REG-011",
    AddressLine1: "Av. Morumbi, 8000",
    AddressLine2: "Morumbi",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Technology"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-012",
    OrganisationName: "PaySecure",
    LegalEntityName: "PaySecure Tecnologia Ltda",
    RegistrationNumber: "01234567890123",
    RegistrationId: "REG-012",
    AddressLine1: "Rua da Consolação, 2000",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Security"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-013",
    OrganisationName: "FinTech Solutions",
    LegalEntityName: "FinTech Solutions Inovação S.A.",
    RegistrationNumber: "12345678901235",
    RegistrationId: "REG-013",
    AddressLine1: "Av. Paulista, 2000",
    AddressLine2: "Bela Vista",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Innovation"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-014",
    OrganisationName: "Digital Solutions",
    LegalEntityName: "Digital Solutions Tecnologia Ltda",
    RegistrationNumber: "23456789012346",
    RegistrationId: "REG-014",
    AddressLine1: "Av. Brigadeiro Faria Lima, 2000",
    AddressLine2: "Jardim Paulistano",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Technology", "Digital"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-015",
    OrganisationName: "Bank Solutions",
    LegalEntityName: "Bank Solutions Serviços S.A.",
    RegistrationNumber: "34567890123457",
    RegistrationId: "REG-015",
    AddressLine1: "Rua Oscar Freire, 1000",
    AddressLine2: "Jardins",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Services"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-016",
    OrganisationName: "Pay Solutions",
    LegalEntityName: "Pay Solutions Tecnologia Ltda",
    RegistrationNumber: "45678901234568",
    RegistrationId: "REG-016",
    AddressLine1: "Av. Rebouças, 1500",
    AddressLine2: "Pinheiros",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Technology"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-017",
    OrganisationName: "FinTech Digital",
    LegalEntityName: "FinTech Digital Inovação S.A.",
    RegistrationNumber: "56789012345679",
    RegistrationId: "REG-017",
    AddressLine1: "Av. Berrini, 2000",
    AddressLine2: "Brooklin",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Digital"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-018",
    OrganisationName: "Tech Solutions",
    LegalEntityName: "Tech Solutions Sistemas Ltda",
    RegistrationNumber: "67890123456790",
    RegistrationId: "REG-018",
    AddressLine1: "Rua Haddock Lobo, 600",
    AddressLine2: "Cerqueira César",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Technology", "Systems"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-019",
    OrganisationName: "Bank Digital",
    LegalEntityName: "Bank Digital Serviços S.A.",
    RegistrationNumber: "78901234567891",
    RegistrationId: "REG-019",
    AddressLine1: "Av. Cidade Jardim, 400",
    AddressLine2: "Jardim Europa",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Digital"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-020",
    OrganisationName: "Pay Digital",
    LegalEntityName: "Pay Digital Tecnologia Ltda",
    RegistrationNumber: "89012345678902",
    RegistrationId: "REG-020",
    AddressLine1: "Rua Bela Cintra, 1200",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Digital"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-021",
    OrganisationName: "FinTech Systems",
    LegalEntityName: "FinTech Systems Inovação S.A.",
    RegistrationNumber: "90123456789013",
    RegistrationId: "REG-021",
    AddressLine1: "Av. Morumbi, 9000",
    AddressLine2: "Morumbi",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Systems"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-022",
    OrganisationName: "Digital Systems",
    LegalEntityName: "Digital Systems Tecnologia Ltda",
    RegistrationNumber: "01234567890124",
    RegistrationId: "REG-022",
    AddressLine1: "Rua da Consolação, 2200",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Systems"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-023",
    OrganisationName: "Bank Systems",
    LegalEntityName: "Bank Systems Serviços S.A.",
    RegistrationNumber: "12345678901236",
    RegistrationId: "REG-023",
    AddressLine1: "Av. Paulista, 2200",
    AddressLine2: "Bela Vista",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Systems"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-024",
    OrganisationName: "Pay Systems",
    LegalEntityName: "Pay Systems Tecnologia Ltda",
    RegistrationNumber: "23456789012347",
    RegistrationId: "REG-024",
    AddressLine1: "Av. Brigadeiro Faria Lima, 2200",
    AddressLine2: "Jardim Paulistano",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Systems"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-025",
    OrganisationName: "FinTech Services",
    LegalEntityName: "FinTech Services Inovação S.A.",
    RegistrationNumber: "34567890123458",
    RegistrationId: "REG-025",
    AddressLine1: "Rua Oscar Freire, 1200",
    AddressLine2: "Jardins",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Services"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-026",
    OrganisationName: "Digital Services",
    LegalEntityName: "Digital Services Tecnologia Ltda",
    RegistrationNumber: "45678901234569",
    RegistrationId: "REG-026",
    AddressLine1: "Av. Rebouças, 1700",
    AddressLine2: "Pinheiros",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Services"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-027",
    OrganisationName: "Bank Services",
    LegalEntityName: "Bank Services Sistemas S.A.",
    RegistrationNumber: "56789012345680",
    RegistrationId: "REG-027",
    AddressLine1: "Av. Berrini, 2200",
    AddressLine2: "Brooklin",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Services"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-028",
    OrganisationName: "Pay Services",
    LegalEntityName: "Pay Services Tecnologia Ltda",
    RegistrationNumber: "67890123456791",
    RegistrationId: "REG-028",
    AddressLine1: "Rua Haddock Lobo, 800",
    AddressLine2: "Cerqueira César",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Services"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-029",
    OrganisationName: "FinTech Innovation",
    LegalEntityName: "FinTech Innovation Sistemas S.A.",
    RegistrationNumber: "78901234567892",
    RegistrationId: "REG-029",
    AddressLine1: "Av. Cidade Jardim, 600",
    AddressLine2: "Jardim Europa",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Innovation"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-030",
    OrganisationName: "Digital Innovation",
    LegalEntityName: "Digital Innovation Tecnologia Ltda",
    RegistrationNumber: "89012345678903",
    RegistrationId: "REG-030",
    AddressLine1: "Rua Bela Cintra, 1400",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Innovation"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-031",
    OrganisationName: "Bank Innovation",
    LegalEntityName: "Bank Innovation Serviços S.A.",
    RegistrationNumber: "90123456789014",
    RegistrationId: "REG-031",
    AddressLine1: "Av. Morumbi, 10000",
    AddressLine2: "Morumbi",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Innovation"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-032",
    OrganisationName: "Pay Innovation",
    LegalEntityName: "Pay Innovation Tecnologia Ltda",
    RegistrationNumber: "01234567890125",
    RegistrationId: "REG-032",
    AddressLine1: "Rua da Consolação, 2400",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Innovation"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-033",
    OrganisationName: "FinTech Security",
    LegalEntityName: "FinTech Security Sistemas S.A.",
    RegistrationNumber: "12345678901237",
    RegistrationId: "REG-033",
    AddressLine1: "Av. Paulista, 2400",
    AddressLine2: "Bela Vista",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Security"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-034",
    OrganisationName: "Digital Security",
    LegalEntityName: "Digital Security Tecnologia Ltda",
    RegistrationNumber: "23456789012348",
    RegistrationId: "REG-034",
    AddressLine1: "Av. Brigadeiro Faria Lima, 2400",
    AddressLine2: "Jardim Paulistano",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Security"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-035",
    OrganisationName: "Bank Security",
    LegalEntityName: "Bank Security Serviços S.A.",
    RegistrationNumber: "34567890123459",
    RegistrationId: "REG-035",
    AddressLine1: "Rua Oscar Freire, 1400",
    AddressLine2: "Jardins",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Security"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-036",
    OrganisationName: "Pay Security",
    LegalEntityName: "Pay Security Tecnologia Ltda",
    RegistrationNumber: "45678901234570",
    RegistrationId: "REG-036",
    AddressLine1: "Av. Rebouças, 1900",
    AddressLine2: "Pinheiros",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Security"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-037",
    OrganisationName: "FinTech Solutions",
    LegalEntityName: "FinTech Solutions Sistemas S.A.",
    RegistrationNumber: "56789012345681",
    RegistrationId: "REG-037",
    AddressLine1: "Av. Berrini, 2400",
    AddressLine2: "Brooklin",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Solutions"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-038",
    OrganisationName: "Digital Solutions",
    LegalEntityName: "Digital Solutions Tecnologia Ltda",
    RegistrationNumber: "67890123456792",
    RegistrationId: "REG-038",
    AddressLine1: "Rua Haddock Lobo, 1000",
    AddressLine2: "Cerqueira César",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Solutions"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-039",
    OrganisationName: "Bank Solutions",
    LegalEntityName: "Bank Solutions Serviços S.A.",
    RegistrationNumber: "78901234567893",
    RegistrationId: "REG-039",
    AddressLine1: "Av. Cidade Jardim, 800",
    AddressLine2: "Jardim Europa",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Solutions"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-040",
    OrganisationName: "Pay Solutions",
    LegalEntityName: "Pay Solutions Tecnologia Ltda",
    RegistrationNumber: "89012345678904",
    RegistrationId: "REG-040",
    AddressLine1: "Rua Bela Cintra, 1600",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Solutions"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-041",
    OrganisationName: "FinTech Digital",
    LegalEntityName: "FinTech Digital Sistemas S.A.",
    RegistrationNumber: "90123456789015",
    RegistrationId: "REG-041",
    AddressLine1: "Av. Morumbi, 11000",
    AddressLine2: "Morumbi",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Digital"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-042",
    OrganisationName: "Digital Systems",
    LegalEntityName: "Digital Systems Tecnologia Ltda",
    RegistrationNumber: "01234567890126",
    RegistrationId: "REG-042",
    AddressLine1: "Rua da Consolação, 2600",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Systems"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-043",
    OrganisationName: "Bank Digital",
    LegalEntityName: "Bank Digital Serviços S.A.",
    RegistrationNumber: "12345678901238",
    RegistrationId: "REG-043",
    AddressLine1: "Av. Paulista, 2600",
    AddressLine2: "Bela Vista",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Digital"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-044",
    OrganisationName: "Pay Digital",
    LegalEntityName: "Pay Digital Tecnologia Ltda",
    RegistrationNumber: "23456789012349",
    RegistrationId: "REG-044",
    AddressLine1: "Av. Brigadeiro Faria Lima, 2600",
    AddressLine2: "Jardim Paulistano",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Digital"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-045",
    OrganisationName: "FinTech Systems",
    LegalEntityName: "FinTech Systems Serviços S.A.",
    RegistrationNumber: "34567890123460",
    RegistrationId: "REG-045",
    AddressLine1: "Rua Oscar Freire, 1600",
    AddressLine2: "Jardins",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Systems"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-046",
    OrganisationName: "Digital Services",
    LegalEntityName: "Digital Services Tecnologia Ltda",
    RegistrationNumber: "45678901234571",
    RegistrationId: "REG-046",
    AddressLine1: "Av. Rebouças, 2100",
    AddressLine2: "Pinheiros",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Services"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-047",
    OrganisationName: "Bank Services",
    LegalEntityName: "Bank Services Sistemas S.A.",
    RegistrationNumber: "56789012345682",
    RegistrationId: "REG-047",
    AddressLine1: "Av. Berrini, 2600",
    AddressLine2: "Brooklin",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Banking", "Services"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-048",
    OrganisationName: "Pay Services",
    LegalEntityName: "Pay Services Tecnologia Ltda",
    RegistrationNumber: "67890123456793",
    RegistrationId: "REG-048",
    AddressLine1: "Rua Haddock Lobo, 1200",
    AddressLine2: "Cerqueira César",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Payments", "Services"],
    Size: "Médio",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-049",
    OrganisationName: "FinTech Innovation",
    LegalEntityName: "FinTech Innovation Sistemas S.A.",
    RegistrationNumber: "78901234567894",
    RegistrationId: "REG-049",
    AddressLine1: "Av. Cidade Jardim, 1000",
    AddressLine2: "Jardim Europa",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Fintech", "Innovation"],
    Size: "Grande",
    AuthorisationServers: []
  },
  {
    OrganisationId: "org-050",
    OrganisationName: "Digital Innovation",
    LegalEntityName: "Digital Innovation Tecnologia Ltda",
    RegistrationNumber: "89012345678905",
    RegistrationId: "REG-050",
    AddressLine1: "Rua Bela Cintra, 1800",
    AddressLine2: "Consolação",
    City: "São Paulo, SP",
    Country: "Brasil",
    Tags: ["Digital", "Innovation"],
    Size: "Médio",
    AuthorisationServers: []
  }
];

export const getOrganizations = async () => {
  try {
    // Retornando dados fictícios em vez de fazer a chamada à API
    return mockOrganizations;
  }
  catch (error) {
    console.log(error)
    return [];
  }
}
